import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../../theme/app_colors.dart';
import '../../providers/management_providers.dart' as mgmt;
import '../../providers/auth_provider.dart';

class StudentReportScreen extends ConsumerStatefulWidget {
  final Map<String, dynamic> student;

  const StudentReportScreen({Key? key, required this.student}) : super(key: key);

  @override
  ConsumerState<StudentReportScreen> createState() => _StudentReportScreenState();
}

class _StudentReportScreenState extends ConsumerState<StudentReportScreen> {

  Future<void> _generatePdf(Map<String, dynamic> details, WidgetRef ref) async {
    final authState = ref.read(authProvider);
    final pdf = pw.Document();
    
    final fullName = widget.student['fullName']?.toString() ?? 'Unknown';
    final rollNo = widget.student['rollNo']?.toString() ?? 'N/A';
    final grade = widget.student['grade']?.toString() ?? 'N/A';
    final batchName = widget.student['batchName']?.toString() ?? 'N/A';
    
    final academics = details['academics'] as Map<String, dynamic>?;
    final overallPct = academics?['overallPercentage']?.toString() ?? '0.0';
    
    final attendanceData = details['attendance'] as Map<String, dynamic>?;
    final attPct = attendanceData?['percentage']?.toString() ?? '0';
    
    final present = int.tryParse(attendanceData?['present']?.toString() ?? '0') ?? 0;
    final absent = int.tryParse(attendanceData?['absent']?.toString() ?? '0') ?? 0;
    final late = int.tryParse(attendanceData?['late']?.toString() ?? '0') ?? 0;
    final totalDays = present + absent + late;
    
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(32),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                if (authState.instituteName != null) ...[
                  pw.Center(
                    child: pw.Text(authState.instituteName!.toUpperCase(), style: pw.TextStyle(fontSize: 28, fontWeight: pw.FontWeight.bold, color: PdfColor.fromHex(authState.primaryColor?.replaceFirst('#', '') ?? '1F2E27'))),
                  ),
                  pw.SizedBox(height: 8),
                ],
                pw.Center(
                  child: pw.Text('STUDENT PERFORMANCE REPORT', style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: PdfColors.grey700)),
                ),
                pw.SizedBox(height: 24),
                pw.Container(
                  padding: const pw.EdgeInsets.all(16),
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.grey300),
                    borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
                  ),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Name: $fullName', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                      pw.SizedBox(height: 8),
                      pw.Text('Class: $grade  |  Batch: $batchName  |  Roll No: $rollNo'),
                    ],
                  ),
                ),
                pw.SizedBox(height: 24),
                pw.Text('Academic Overview', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                pw.Divider(),
                pw.SizedBox(height: 8),
                pw.Text('Overall Percentage: $overallPct%', style: pw.TextStyle(fontSize: 14)),
                pw.SizedBox(height: 24),
                pw.Text('Attendance Overview', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                pw.Divider(),
                pw.SizedBox(height: 8),
                pw.Text('Attendance Percentage: $attPct%', style: pw.TextStyle(fontSize: 14)),
                pw.SizedBox(height: 8),
                pw.Text('Total Working Days: $totalDays', style: pw.TextStyle(fontSize: 14)),
                pw.SizedBox(height: 4),
                pw.Text('Present: $present  |  Absent: $absent  |  Late: $late', style: pw.TextStyle(fontSize: 14)),
                pw.Spacer(),
                pw.Divider(),
                pw.Center(child: pw.Text('Generated by EdTech OS on ${DateFormat('dd MMM yyyy').format(DateTime.now())}', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600))),
              ],
            ),
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Report_$fullName',
    );
  }

  @override
  Widget build(BuildContext context) {
    final studentId = widget.student['id'] as int;
    final detailsAsync = ref.watch(mgmt.studentDetailsProvider(studentId));
    
    final fullName = widget.student['fullName']?.toString() ?? 'Unknown Student';
    final rollNo = widget.student['rollNo']?.toString() ?? 'N/A';
    final grade = widget.student['grade']?.toString() ?? 'N/A';
    final batchName = widget.student['batchName']?.toString() ?? 'N/A';

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: const Text('Performance Report', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
        backgroundColor: AppColors.primaryDark,
        iconTheme: const IconThemeData(color: Colors.white),
      ),
      body: detailsAsync.when(
        data: (details) {
          final academics = details['academics'] as Map<String, dynamic>?;
          final overallPct = academics?['overallPercentage']?.toString() ?? '0.0';
          
          final attendanceData = details['attendance'] as Map<String, dynamic>?;
          final attPct = attendanceData?['percentage']?.toString() ?? '0';

          return SingleChildScrollView(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Header Card
                Container(
                  padding: const EdgeInsets.all(20),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(20),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withValues(alpha: 0.05),
                        blurRadius: 10,
                        offset: const Offset(0, 4),
                      ),
                    ],
                  ),
                  child: Row(
                    children: [
                      Container(
                        width: 72,
                        height: 72,
                        decoration: const BoxDecoration(
                          color: AppColors.successLight,
                          shape: BoxShape.circle,
                        ),
                        child: const Icon(Icons.person, size: 40, color: AppColors.primaryDark),
                      ),
                      const SizedBox(width: 16),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(fullName, style: const TextStyle(fontSize: 22, fontWeight: FontWeight.bold, color: AppColors.primaryDark)),
                            const SizedBox(height: 4),
                            Text('Roll No: $rollNo  •  Class $grade', style: TextStyle(color: Colors.grey.shade700, fontSize: 12)),
                            const SizedBox(height: 2),
                            Text('Batch: $batchName', style: TextStyle(color: Colors.grey.shade700, fontSize: 12)),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
                
                const SizedBox(height: 24),
                
                // Academics Section
                const Text('Academic Performance', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: AppColors.primaryDark)),
                const SizedBox(height: 12),
                Container(
                  padding: const EdgeInsets.all(20),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(20),
                    boxShadow: [
                      BoxShadow(color: Colors.black.withValues(alpha: 0.05), blurRadius: 10, offset: const Offset(0, 4)),
                    ],
                  ),
                  child: Column(
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          const Text('Overall Score', style: TextStyle(fontSize: 14, color: Colors.grey)),
                          Text('$overallPct%', style: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: AppColors.primary)),
                        ],
                      ),
                      const SizedBox(height: 24),
                      SizedBox(
                        height: 140,
                        child: LineChart(
                          LineChartData(
                            gridData: const FlGridData(show: false),
                            titlesData: const FlTitlesData(show: false),
                            borderData: FlBorderData(show: false),
                            lineBarsData: [
                              LineChartBarData(
                                spots: const [
                                  FlSpot(0, 40),
                                  FlSpot(1, 60),
                                  FlSpot(2, 50),
                                  FlSpot(3, 80),
                                  FlSpot(4, 75),
                                  FlSpot(5, 90),
                                ],
                                isCurved: true,
                                color: AppColors.primary,
                                barWidth: 4,
                                isStrokeCapRound: true,
                                dotData: const FlDotData(show: true),
                                belowBarData: BarAreaData(
                                  show: true,
                                  gradient: LinearGradient(
                                    colors: [
                                      AppColors.primary.withValues(alpha: 0.3),
                                      AppColors.primary.withValues(alpha: 0.0),
                                    ],
                                    begin: Alignment.topCenter,
                                    end: Alignment.bottomCenter,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
                
                const SizedBox(height: 24),
                
                // Attendance Section
                const Text('Attendance Insights', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: AppColors.primaryDark)),
                const SizedBox(height: 12),
                Container(
                  padding: const EdgeInsets.all(20),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(20),
                    boxShadow: [
                      BoxShadow(color: Colors.black.withValues(alpha: 0.05), blurRadius: 10, offset: const Offset(0, 4)),
                    ],
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceAround,
                    children: [
                      SizedBox(
                        height: 100,
                        width: 100,
                        child: Stack(
                          fit: StackFit.expand,
                          children: [
                            CircularProgressIndicator(
                              value: (double.tryParse(attPct) ?? 0) / 100,
                              strokeWidth: 10,
                              backgroundColor: Colors.grey.shade200,
                              color: AppColors.success,
                            ),
                            Center(
                              child: Text(
                                '$attPct%',
                                style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: AppColors.primaryDark),
                              ),
                            ),
                          ],
                        ),
                      ),
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          _buildAttStat('Present', details['attendance']?['present']?.toString() ?? '0', AppColors.success),
                          const SizedBox(height: 8),
                          _buildAttStat('Absent', details['attendance']?['absent']?.toString() ?? '0', Colors.red),
                          const SizedBox(height: 8),
                          _buildAttStat('Late', details['attendance']?['late']?.toString() ?? '0', Colors.orange),
                        ],
                      )
                    ],
                  ),
                ),
                
                const SizedBox(height: 40),
                
                SizedBox(
                  width: double.infinity,
                  height: 56,
                  child: ElevatedButton.icon(
                    onPressed: () => _generatePdf(details, ref),
                    icon: const Icon(Icons.download, color: Colors.white),
                    label: const Text('Download PDF Report', style: TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.bold)),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.primaryDark,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                      elevation: 4,
                    ),
                  ),
                ),
                const SizedBox(height: 20),
              ],
            ),
          );
        },
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (err, stack) => Center(child: Text('Failed to load report data: $err')),
      ),
    );
  }

  Widget _buildAttStat(String label, String value, Color color) {
    return Row(
      children: [
        Container(width: 12, height: 12, decoration: BoxDecoration(color: color, shape: BoxShape.circle)),
        const SizedBox(width: 8),
        Text('$label: $value', style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w500)),
      ],
    );
  }
}
